tap 'homebrew/cask-fonts'
tap 'heroku/brew'
tap 'beeftornado/rmtree'

cask 'alfred'
cask 'authy'
cask 'appcleaner'
cask 'aptible'
cask 'browserstacklocal'
cask 'discord'
cask 'dozer'
cask 'firefox'
cask 'font-hack'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'itsycal'
cask 'playonmac'
cask 'slack'
cask 'spectacle'
cask 'zoomus'

brew 'bash'
brew 'bash-completion'
brew 'git'
brew 'heroku'
brew 'hub'
brew 'neofetch'
brew 'neovim'
brew 'postgresql', restart_service: :changed
brew 'rbenv'
brew 'redis', restart_service: :changed
brew 'the_silver_searcher'
brew 'tmux'
brew 'yarn', args: ['ignore-dependencies']
